apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-light-config
data:
  config.json: |
    {
      "OPENTELEMETRY_COLLECTOR_EXPORT_LOGS_INTERVAL_SECONDS": "60",
      "OPENTELEMETRY_COLLECTOR_EXPORT_METRICS_INTERVAL_SECONDS": "60",
      "METRICS_COMPRESS_MINUTE_THRESHOLD_HOURS": "12",
      "METRICS_COMPRESS_HOUR_THRESHOLD_DAYS": "7",
      "OPENTELEMETRY_COLLECT_AUTHORIZATION_HEADER": "",
      "MAINTENANCE_FREQUENCY_HOURS": "6"
    }
